== Advanced Topics

This section is about things that can be implemented to improve and augment the app.

=== Testing

If the application is getting big then it is time to think about automated testing. It helps to ensure
that the app performs correctly without errors.
There are 3 ways to test a flutter app: Unit, Widget and Integration tests.

For more information visit: https://flutter.dev/docs/testing

.Comparison
[cols="20,20,20,20", options="header"]
|===
|
| Unit
| Widget
| Integration

| Confidence
| Low
| Higher
| Highest

| Maintenance cost
| Low
| Higher
| Highest

| Dependencies
| Few
| More
| Most

| Execution speed
| Quick
| Slower
| Slowest
|===

==== Unit Test

The smallest and fastest test. The goal is to test a single function, method or class.

More info: https://flutter.dev/docs/cookbook/testing/unit/introduction

==== Widget Test

The goal of this test is to ensure that the UI works properly, for example user interaction.

More info: https://flutter.dev/docs/cookbook/testing/widget/introduction

==== Integration Test

The biggest test is an integration test. The goal is to test a large part of the application and
to see if the components are working in harmony.

More info: https://flutter.dev/docs/cookbook/testing/integration/introduction

=== Animations with Flare

==== What is Flare?

[quote, Official Website]
Flare is a powerful design and animation tool, which allows designers and developers to easily add high-quality animation to their apps and games.

==== Why should you use it?

It allows to create awesome looking animations in a short period of time. It is really easy to learn and the animations
are super smooth!

==== Implementation

It is really simple. Just add the package called `flare_flutter`, add the widget and make a reference to the Flare file.

*Done.* So easy and fast.

.example.dart
[source,dart]
----
import 'package:flare_flutter/flare_actor.dart';
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new FlareActor("assets/Filip.flr", alignment:Alignment.center, fit:BoxFit.contain, animation:"idle");
  }
}
----

Plugin: https://pub.dev/packages/flare_flutter +
Example Animations: https://www.2dimensions.com/explore/popular/trending/all

=== REST & GraphQL

==== REST

The application will probably need some communication with an external interface. The most common way is to do
it with REST. +
Example guide: https://flutter.dev/docs/cookbook/networking/fetch-data

==== GraphQL

The other really trending way is to use GraphQl. The advantage is that you only get the specific data you want.
This minimizes the transfer of data over the internet!

The only way at the moment to use GraphQl is to implement the package `graphql_flutter`. +
Package: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter

The package is [.line-through]#stolen# heavily inspired by Apollo, the biggest player in GraphQL integration in web development.

=== Continuous Integration & Continuous Development

It is possible to automatically build and publish the application. There are multiple ways to achieve this like for example with:

* Fastlane
* GitLab
* Codemagic
* Bitrise

The easiest way to integrate CI/CD is to use Codemagic. It offers all the tools you need and there is a free plan. +
Codemagic: https://codemagic.io/start/

The official flutter site published a really good guide to setup Fastlane: https://flutter.dev/docs/deployment/cd

=== Internationalizing

Internationalizing is the technical term for supporting multiple speaking languages.
Here is a good guide on how to support multiple languages: https://flutter.dev/docs/development/accessibility-and-localization/internationalization